// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stage_2_final_project_tgbooks_backend.Data;

#nullable disable

namespace stage_2_final_project_tgbooks_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260306193522_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BookCategory");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Dystopian"
                        },
                        new
                        {
                            Id = 7,
                            Type = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Type = "Thriller"
                        },
                        new
                        {
                            Id = 9,
                            Type = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            Type = "Biography"
                        },
                        new
                        {
                            Id = 11,
                            Type = "Autobiography"
                        },
                        new
                        {
                            Id = 12,
                            Type = "History"
                        },
                        new
                        {
                            Id = 13,
                            Type = "Philosophy"
                        },
                        new
                        {
                            Id = 14,
                            Type = "Science"
                        },
                        new
                        {
                            Id = 15,
                            Type = "Technology"
                        },
                        new
                        {
                            Id = 16,
                            Type = "Psychology"
                        },
                        new
                        {
                            Id = 17,
                            Type = "Self-Help"
                        },
                        new
                        {
                            Id = 18,
                            Type = "Business"
                        },
                        new
                        {
                            Id = 19,
                            Type = "Economics"
                        },
                        new
                        {
                            Id = 20,
                            Type = "Politics"
                        },
                        new
                        {
                            Id = 21,
                            Type = "Religion"
                        },
                        new
                        {
                            Id = 22,
                            Type = "Spirituality"
                        },
                        new
                        {
                            Id = 23,
                            Type = "Education"
                        },
                        new
                        {
                            Id = 24,
                            Type = "Children"
                        },
                        new
                        {
                            Id = 25,
                            Type = "Young Adult"
                        },
                        new
                        {
                            Id = 26,
                            Type = "Adventure"
                        },
                        new
                        {
                            Id = 27,
                            Type = "Crime"
                        },
                        new
                        {
                            Id = 28,
                            Type = "True Crime"
                        },
                        new
                        {
                            Id = 29,
                            Type = "Classic"
                        },
                        new
                        {
                            Id = 30,
                            Type = "Drama"
                        },
                        new
                        {
                            Id = 31,
                            Type = "Comedy"
                        },
                        new
                        {
                            Id = 32,
                            Type = "Poetry"
                        },
                        new
                        {
                            Id = 33,
                            Type = "Short Stories"
                        },
                        new
                        {
                            Id = 34,
                            Type = "Graphic Novel"
                        },
                        new
                        {
                            Id = 35,
                            Type = "Manga"
                        },
                        new
                        {
                            Id = 36,
                            Type = "Mythology"
                        },
                        new
                        {
                            Id = 37,
                            Type = "Fairy Tales"
                        },
                        new
                        {
                            Id = 38,
                            Type = "Anthology"
                        },
                        new
                        {
                            Id = 39,
                            Type = "Western"
                        },
                        new
                        {
                            Id = 40,
                            Type = "Detective"
                        },
                        new
                        {
                            Id = 41,
                            Type = "Historical Fiction"
                        },
                        new
                        {
                            Id = 42,
                            Type = "Political Fiction"
                        },
                        new
                        {
                            Id = 43,
                            Type = "Science Popular"
                        },
                        new
                        {
                            Id = 44,
                            Type = "Health"
                        },
                        new
                        {
                            Id = 45,
                            Type = "Parenting"
                        },
                        new
                        {
                            Id = 46,
                            Type = "Environmental"
                        },
                        new
                        {
                            Id = 47,
                            Type = "Travel"
                        },
                        new
                        {
                            Id = 48,
                            Type = "Cooking"
                        });
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsVerified] = 1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Address", b =>
                {
                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.User", null)
                        .WithOne("Address")
                        .HasForeignKey("stage_2_final_project_tgbooks_backend.Data.Models.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Order", b =>
                {
                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.OrderItem", b =>
                {
                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("stage_2_final_project_tgbooks_backend.Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("stage_2_final_project_tgbooks_backend.Data.Models.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
